# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3849d40285cacd9ad7b3edbcf25a26d2c7a862a2898fd3b43b99ff589764036ba9fbfe8cc63b358a4e1beeb1b35acbd31d185191a81b1cdbd1c754956dbf47f8

test:
  secret_key_base: db9cde1a3a1eaf2cfafe8cb35e4709faa8329173ab43956270ee32f159850b9ed15b5b3b90093819734d6f3ed7795c7074d27f6a87f2aea09190884cca490879

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
